<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RabbitMqExample.Contracts\RabbitMqExample.Contracts.csproj" />
    <ProjectReference Include="..\RabbitMqExample.Messaging\RabbitMqExample.Messaging.csproj" />
  </ItemGroup>
</Project>
