<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
      Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets"
      Version="1.23.0"
    />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RabbitMqExample.Contracts\RabbitMqExample.Contracts.csproj" />
    <ProjectReference Include="..\RabbitMqExample.Messaging\RabbitMqExample.Messaging.csproj" />
  </ItemGroup>
</Project>
